version: "3.9"
networks:
  auto-data-augmentation-internal:


services:
  runner:
    container_name: feature-discovery-runner
    depends_on: [neo4j]
    build:
      context: .
      dockerfile: docker/Dockerfile
    tty: true
    restart: always
    volumes:
      - ./src:/src
      - ./data:/data
      - ./results:/results

  neo4j:
    container_name: feature-discovery-neo4j
    image: neo4j:5.3.0-enterprise
    hostname: feature-discovery-neo4j
    volumes:
      - ./neo4j-db:/neo4j-db
      - ./neo4j-data:/data
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_security_auth__enabled=false
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    tty: true

volumes:
  src:
  neo4j-db:
  neo4j-data:
  data:
  results: