version: "3.9"
services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/feature-discovery
    tty: true
    restart: always

  neo4j:
    image: neo4j:5.1.0-enterprise
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/pass
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,gds.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
